/**
 * TrueReact - Session Export Service
 * 
 * Export session insights to device notes/share sheet
 * or save as text for later reference.
 */

import { Share, Platform, Alert } from 'react-native';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';

export type SessionInsight = {
  observation: string;
  suggestion: string;
  category: string;
  timestamp: number;
};

export type SessionExportData = {
  sessionId: string;
  date: string;
  duration: number; // seconds
  insights: SessionInsight[];
  emotionSummary?: {
    dominantEmotion: string;
    averageIntensity: number;
    congruenceScore: number;
    maskingOccurrences: number;
  };
  moodBefore?: number;
  moodAfter?: number;
  techniques?: string[];
};

/**
 * Format session data as readable text
 */
export function formatSessionForExport(data: SessionExportData): string {
  const lines: string[] = [];
  
  // Header
  lines.push('═══════════════════════════════════════');
  lines.push('         TrueReact Session Summary        ');
  lines.push('═══════════════════════════════════════');
  lines.push('');
  
  // Session info
  lines.push(`📅 Date: ${data.date}`);
  lines.push(`⏱️ Duration: ${formatDuration(data.duration)}`);
  lines.push(`🔖 Session ID: ${data.sessionId.slice(0, 8)}...`);
  lines.push('');
  
  // Mood tracking
  if (data.moodBefore !== undefined || data.moodAfter !== undefined) {
    lines.push('───────────────────────────────────────');
    lines.push('💭 MOOD TRACKING');
    lines.push('───────────────────────────────────────');
    if (data.moodBefore !== undefined) {
      lines.push(`   Before: ${getMoodEmoji(data.moodBefore)} (${data.moodBefore}/5)`);
    }
    if (data.moodAfter !== undefined) {
      lines.push(`   After:  ${getMoodEmoji(data.moodAfter)} (${data.moodAfter}/5)`);
    }
    if (data.moodBefore !== undefined && data.moodAfter !== undefined) {
      const diff = data.moodAfter - data.moodBefore;
      const trend = diff > 0 ? '↑ improved' : diff < 0 ? '↓ declined' : '→ stable';
      lines.push(`   Change: ${trend}`);
    }
    lines.push('');
  }
  
  // Emotion summary
  if (data.emotionSummary) {
    lines.push('───────────────────────────────────────');
    lines.push('🎭 EMOTION ANALYSIS');
    lines.push('───────────────────────────────────────');
    lines.push(`   Dominant: ${capitalize(data.emotionSummary.dominantEmotion)}`);
    lines.push(`   Intensity: ${Math.round(data.emotionSummary.averageIntensity * 100)}%`);
    lines.push(`   Congruence: ${Math.round(data.emotionSummary.congruenceScore * 100)}%`);
    if (data.emotionSummary.maskingOccurrences > 0) {
      lines.push(`   Masking detected: ${data.emotionSummary.maskingOccurrences} times`);
    }
    lines.push('');
  }
  
  // Coaching insights
  if (data.insights.length > 0) {
    lines.push('───────────────────────────────────────');
    lines.push('💡 COACHING INSIGHTS');
    lines.push('───────────────────────────────────────');
    lines.push('');
    
    data.insights.forEach((insight, index) => {
      const icon = getCategoryIcon(insight.category);
      lines.push(`${index + 1}. ${icon} ${capitalize(insight.category)}`);
      lines.push(`   Observation: ${insight.observation}`);
      lines.push(`   Suggestion: ${insight.suggestion}`);
      lines.push('');
    });
  }
  
  // Techniques used
  if (data.techniques && data.techniques.length > 0) {
    lines.push('───────────────────────────────────────');
    lines.push('📚 TECHNIQUES PRACTICED');
    lines.push('───────────────────────────────────────');
    data.techniques.forEach(technique => {
      lines.push(`   • ${technique}`);
    });
    lines.push('');
  }
  
  // Footer
  lines.push('───────────────────────────────────────');
  lines.push('Generated by TrueReact');
  lines.push('Your authentic self, expressed clearly');
  lines.push('═══════════════════════════════════════');
  
  return lines.join('\n');
}

/**
 * Export session via native share sheet
 */
export async function shareSession(data: SessionExportData): Promise<boolean> {
  try {
    const content = formatSessionForExport(data);
    
    const result = await Share.share({
      message: content,
      title: `TrueReact Session - ${data.date}`,
    });
    
    return result.action === Share.sharedAction;
  } catch (error) {
    console.error('Failed to share session:', error);
    return false;
  }
}

/**
 * Copy session to clipboard
 */
export async function copySessionToClipboard(data: SessionExportData): Promise<boolean> {
  try {
    const content = formatSessionForExport(data);
    await Clipboard.setStringAsync(content);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Save session as text file
 */
export async function saveSessionAsFile(data: SessionExportData): Promise<string | null> {
  try {
    const content = formatSessionForExport(data);
    const filename = `truereact_session_${data.sessionId.slice(0, 8)}_${data.date.replace(/\//g, '-')}.txt`;
    const fileUri = `${FileSystem.documentDirectory}${filename}`;
    
    await FileSystem.writeAsStringAsync(fileUri, content, {
      encoding: FileSystem.EncodingType.UTF8,
    });
    
    // Check if sharing is available
    const isAvailable = await Sharing.isAvailableAsync();
    
    if (isAvailable) {
      await Sharing.shareAsync(fileUri, {
        mimeType: 'text/plain',
        dialogTitle: 'Save Session Notes',
      });
    }
    
    return fileUri;
  } catch (error) {
    console.error('Failed to save session file:', error);
    return null;
  }
}

/**
 * Export as JSON (for data portability)
 */
export async function exportSessionAsJson(data: SessionExportData): Promise<boolean> {
  try {
    const jsonContent = JSON.stringify(data, null, 2);
    
    const result = await Share.share({
      message: jsonContent,
      title: `TrueReact Data - ${data.date}`,
    });
    
    return result.action === Share.sharedAction;
  } catch (error) {
    console.error('Failed to export JSON:', error);
    return false;
  }
}

/**
 * Quick share single insight
 */
export async function shareSingleInsight(insight: SessionInsight): Promise<boolean> {
  try {
    const content = [
      '💡 TrueReact Insight',
      '',
      `${getCategoryIcon(insight.category)} ${capitalize(insight.category)}`,
      '',
      `Observation: ${insight.observation}`,
      `Tip: ${insight.suggestion}`,
      '',
      '— TrueReact',
    ].join('\n');
    
    const result = await Share.share({
      message: content,
      title: 'TrueReact Insight',
    });
    
    return result.action === Share.sharedAction;
  } catch (error) {
    console.error('Failed to share insight:', error);
    return false;
  }
}

// Helper functions

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  
  if (mins === 0) {
    return `${secs} seconds`;
  } else if (secs === 0) {
    return `${mins} minutes`;
  } else {
    return `${mins}m ${secs}s`;
  }
}

function getMoodEmoji(level: number): string {
  const emojis = ['', '😔', '😕', '😐', '🙂', '😊'];
  return emojis[level] || '😐';
}

function getCategoryIcon(category: string): string {
  const icons: Record<string, string> = {
    expression: '🎭',
    voice: '🎤',
    posture: '🧍',
    general: '💡',
    emotion: '❤️',
    communication: '💬',
  };
  return icons[category.toLowerCase()] || '💡';
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export default {
  formatSessionForExport,
  shareSession,
  copySessionToClipboard,
  saveSessionAsFile,
  exportSessionAsJson,
  shareSingleInsight,
};
